services:
  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN}
      - HF_HOME=/app/model/huggingface
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - /app/model/huggingface:/app/model/huggingface
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
      chromadb:
        condition: service_started
      minio:
        condition: service_started
    restart: on-failure
    runtime: nvidia
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 60s

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app_network

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ragwebui
      - MYSQL_USER=ragwebui
      - MYSQL_PASSWORD=ragwebui
      - TZ=Asia/Shanghai
    ports:
      - "4406:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "$$MYSQL_USER",
          "--password=$$MYSQL_PASSWORD",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8009:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - app_network

  # For Qdrant, Remove the comment and run the following command to start the service
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   ports:
  #     - "6333:6333" # REST API
  #     - "6334:6334" # GRPC
  #   volumes:
  #     - qdrant_data:/qdrant/storage
  #   environment:
  #     - QDRANT_ALLOW_RECOVERY_MODE=true
  #   networks:
  #     - app_network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
      minio:
        condition: service_started
    networks:
      - app_network

volumes:
  mysql_data:
  chroma_data:
  minio_data:
  # qdrant_data:

networks:
  app_network:
    driver: bridge
